### ISSUE TITLE
Error message? Traceback (most recent call last): ~~~

### ISSUE THREAD

**Issue by JaeYoungLee79** [Kinovarobotics/kortex#128]
Dear Sir

I have a new PC and download Kortex.zip and api file
And command "python3 -m pip install kortex_api-2.3.0.post34-py3-none-any.whl"
And it run a example as below.

## Description
rut@rut-Default-string:~/kortex-master/api_python/examples/102-Movement_high_level$ python3 04-send_joint_speeds.py 
Traceback (most recent call last):
  File "/home/rut/kortex-master/api_python/examples/102-Movement_high_level/04-send_joint_speeds.py", line 20, in <module>
    from kortex_api.autogen.client_stubs.BaseClientRpc import BaseClient
  File "/home/rut/.local/lib/python3.10/site-packages/kortex_api/autogen/client_stubs/BaseClientRpc.py", line 6, in <module>
    from ... import  RouterClient
  File "/home/rut/.local/lib/python3.10/site-packages/kortex_api/RouterClient.py", line 3, in <module>
    from .autogen.messages import Frame_pb2 as FramePb  # NOQA
  File "/home/rut/.local/lib/python3.10/site-packages/kortex_api/autogen/messages/Frame_pb2.py", line 9, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/rut/.local/lib/python3.10/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/home/rut/.local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 62, in <module>
    from google.protobuf.internal import containers
  File "/home/rut/.local/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping

## Version
---------------------------------------------------------------------------
rut@rut-Default-string:~/kortex-master/api_python/examples/102-Movement_high_level$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
---------------------------------------------------------------------------
rut@rut-Default-string:~/kortex-master/api_python/examples/102-Movement_high_level$ python3 --version
Python 3.10.6
---------------------------------------------------------------------------
rut@rut-Default-string:~/kortex-master/api_python/examples/102-Movement_high_level$ python3 -m pip install kortex_api-2.3.0.post34-py3-none-any.whl
---------------------------------------------------------------------------

Thanks
Best Regards

**Comment by JaeYoungLee79** [comment]
I changed to ubuntu 18.04 
and it works
